use crate::{PathRule, QueryPolicy};
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InjectionMethod {
    Header,
    Query,
}

#[derive(Clone, Debug, Serialize, PartialEq, Eq)]
pub struct ServicePreset {
    pub id: &'static str,
    pub display: &'static str,
    pub detection_hints: &'static [&'static str],
    pub hosts: &'static [&'static str],
    pub schemes: &'static [&'static str],
    pub ports: &'static [u16],
    pub methods: &'static [&'static str],
    pub paths: &'static [&'static str],
    pub query_policy: QueryPolicy,
    pub injection_method: InjectionMethod,
    pub inject_header: &'static str,
    pub inject_prefix: &'static str,
    pub recommended_ttl_minutes: i64,
    pub recommended_max_uses: u64,
    pub notes: &'static str,
}

pub const PRESETS: &[ServicePreset] = &[
    ServicePreset {
        id: "openai",
        display: "OpenAI",
        detection_hints: &["sk-", "sk-proj-"],
        hosts: &["api.openai.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["POST"],
        paths: &["/v1/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 30,
        recommended_max_uses: 10,
        notes: "OpenAI API bearer token",
    },
    ServicePreset {
        id: "anthropic",
        display: "Anthropic",
        detection_hints: &["sk-ant-"],
        hosts: &["api.anthropic.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["POST"],
        paths: &["/v1/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "x-api-key",
        inject_prefix: "",
        recommended_ttl_minutes: 30,
        recommended_max_uses: 10,
        notes: "Anthropic API key",
    },
    ServicePreset {
        id: "github",
        display: "GitHub",
        detection_hints: &["ghp_", "github_pat_"],
        hosts: &["api.github.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "GitHub token",
    },
    ServicePreset {
        id: "gitlab",
        display: "GitLab",
        detection_hints: &["glpat-"],
        hosts: &["gitlab.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/api/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "PRIVATE-TOKEN",
        inject_prefix: "",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "GitLab access token",
    },
    ServicePreset {
        id: "slack",
        display: "Slack",
        detection_hints: &["xoxb-", "xoxp-"],
        hosts: &["slack.com", "api.slack.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["POST"],
        paths: &["/api/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Slack token",
    },
    ServicePreset {
        id: "stripe",
        display: "Stripe",
        detection_hints: &["sk_live_", "sk_test_"],
        hosts: &["api.stripe.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "DELETE"],
        paths: &["/v1/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Stripe secret key",
    },
    ServicePreset {
        id: "aws",
        display: "AWS",
        detection_hints: &["AKIA", "ASIA", "secret_access_key"],
        hosts: &["*.amazonaws.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::Any,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "",
        recommended_ttl_minutes: 5,
        recommended_max_uses: 5,
        notes: "Use for pre-signed or adapter-mediated AWS flows",
    },
    ServicePreset {
        id: "gcp",
        display: "GCP",
        detection_hints: &["AIza", "Bearer "],
        hosts: &["*.googleapis.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::Any,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Google API or OAuth bearer token",
    },
    ServicePreset {
        id: "azure",
        display: "Azure",
        detection_hints: &["Bearer "],
        hosts: &["management.azure.com", "*.azure.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::Any,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Azure bearer token",
    },
    ServicePreset {
        id: "cloudflare",
        display: "Cloudflare",
        detection_hints: &["cfp_"],
        hosts: &["api.cloudflare.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/client/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Cloudflare API token",
    },
    ServicePreset {
        id: "vercel",
        display: "Vercel",
        detection_hints: &["vercel_"],
        hosts: &["api.vercel.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/v*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Vercel token",
    },
    ServicePreset {
        id: "netlify",
        display: "Netlify",
        detection_hints: &["ntl_"],
        hosts: &["api.netlify.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/api/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Netlify token",
    },
    ServicePreset {
        id: "supabase",
        display: "Supabase",
        detection_hints: &["sbp_", "apikey"],
        hosts: &["*.supabase.co"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "apikey",
        inject_prefix: "",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Supabase API key",
    },
    ServicePreset {
        id: "discord",
        display: "Discord",
        detection_hints: &["Bearer ", "eyJ"],
        hosts: &["discord.com", "discordapp.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST"],
        paths: &["/api/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bot ",
        recommended_ttl_minutes: 15,
        recommended_max_uses: 20,
        notes: "Discord bot token",
    },
    ServicePreset {
        id: "generic-bearer",
        display: "Generic Bearer",
        detection_hints: &["Bearer ", "token"],
        hosts: &[],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::Any,
        injection_method: InjectionMethod::Header,
        inject_header: "Authorization",
        inject_prefix: "Bearer ",
        recommended_ttl_minutes: 10,
        recommended_max_uses: 10,
        notes: "Vendor-agnostic bearer token preset",
    },
    ServicePreset {
        id: "generic-api-key-header",
        display: "Generic API Key Header",
        detection_hints: &["api_key", "apikey", "x-api-key"],
        hosts: &[],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET", "POST", "PUT", "PATCH", "DELETE"],
        paths: &["/*"],
        query_policy: QueryPolicy::Any,
        injection_method: InjectionMethod::Header,
        inject_header: "x-api-key",
        inject_prefix: "",
        recommended_ttl_minutes: 10,
        recommended_max_uses: 10,
        notes: "Vendor-agnostic API key header preset",
    },
    ServicePreset {
        id: "generic-query-api-key",
        display: "Generic Query API Key",
        detection_hints: &["api_key", "apikey"],
        hosts: &[],
        schemes: &["https"],
        ports: &[443],
        methods: &["GET"],
        paths: &["/*"],
        query_policy: QueryPolicy::Prefix,
        injection_method: InjectionMethod::Query,
        inject_header: "api_key",
        inject_prefix: "",
        recommended_ttl_minutes: 5,
        recommended_max_uses: 5,
        notes: "Vendor-agnostic query-string API key preset",
    },
    ServicePreset {
        id: "gemini",
        display: "Google Gemini / Antigravity",
        detection_hints: &["AIza"],
        hosts: &["generativelanguage.googleapis.com"],
        schemes: &["https"],
        ports: &[443],
        methods: &["POST"],
        paths: &["/v1beta/*", "/v1/*"],
        query_policy: QueryPolicy::None,
        injection_method: InjectionMethod::Header,
        inject_header: "x-goog-api-key",
        inject_prefix: "",
        recommended_ttl_minutes: 30,
        recommended_max_uses: 10,
        notes: "Google Gemini API key — used by Antigravity (agy) and direct Gemini callers",
    },
];

pub fn preset(id: &str) -> Option<&'static ServicePreset> {
    PRESETS
        .iter()
        .find(|preset| preset.id.eq_ignore_ascii_case(id))
}

pub fn default_path_rules(paths: &[&str]) -> Vec<PathRule> {
    paths
        .iter()
        .map(|path| {
            if *path == "*" || *path == "/*" {
                PathRule::any()
            } else if path.contains('*') {
                PathRule::wildcard((*path).to_string())
            } else {
                PathRule::exact((*path).to_string())
            }
        })
        .collect()
}
